const Media = {
  vector1: require("../assets/img/Vector1.png"),
  vector2: require("../assets/img/Vector2.png"),
  boy: require("../assets/img/boy.png"),
  glassesimoji: require("../assets/img/glassesimoji.png"),
  crown: require("../assets/img/crown.png"),
  thumbup: require("../assets/img/thumbup.png"),
  heartemoji: require("../assets/img/heartemoji.png"),
  Glasses: require("../assets/img/glasses.png"),
  Humble: require("../assets/img/humble.png"),
  github: require("../assets/img/github.png"),
  linkedin: require("../assets/img/linkedin.png"),
  instagram: require("../assets/img/instagram.png"),
  man: require("../assets/img/man.jpeg"),
  anime: require("../assets/img/anime.png"),
  ui_ux_design: require("../assets/img/ui_ux_design.png"),
  ui_ux_design_2: require("../assets/img/ui_ux_design_2.png"),
  developer: require("../assets/img/developer.png"),
  react_image: require("../assets/img/react_image.png"),
  Figma: require("../assets/img/Figma.png"),
  nodejs_image: require("../assets/img/nodejs_image.png"),
  javascript: require("../assets/img/javascript.png"),
};

export default Media;
