export default {
  cashfree: require("../assets/skills/cashfree.jpg"),
  ccavenue: require("../assets/skills/ccavenue.jpg"),
  express: require("../assets/skills/express.jpg"),
  figma: require("../assets/skills/figma.jpg"),
  firebase: require("../assets/skills/firebase.jpg"),
  git: require("../assets/skills/git.jpg"),
  github: require("../assets/skills/github.jpg"),
  gitlab: require("../assets/skills/gitlab.jpg"),
  javascript: require("../assets/skills/javascript.jpg"),
  mongoDB: require("../assets/skills/mongoDB.jpg"),
  nestJS: require("../assets/skills/nestJS.jpg"),
  nodejs: require("../assets/skills/nodejs.jpg"),
  phpmyadmin: require("../assets/skills/phpmyadmin.jpg"),
  postman: require("../assets/skills/postman.jpg"),
  razorpay: require("../assets/skills/razorpay.jpg"),
  react: require("../assets/skills/React.jpg"),
  redis: require("../assets/skills/redis.jpg"),
  stripe: require("../assets/skills/stripe.jpg"),
  maps: require("../assets/skills/maps.png"),
  netlify: require("../assets/skills/netlify.png"),
  mysql: require("../assets/skills/mysql.png"),
};
